my_string = input("Пст, как дела? ") # (Лучше всех)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string [0:1])
print(my_string [-1]) # print(my_string [len(my_string) -1]) Или как то так)